apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.nameOverride }}-secret
type: Opaque
data:
  {{- range $key, $val := .Values.secrets }}
    {{ $key }}: {{ $val | b64enc | quote }}
    {{- end }}