apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM2akNDQWRLZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJMU1URXhNekUzTlRRMU9Gb1hEVE0xTVRFeE1URTNOVGsxT0Zvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBT0cyCmtGbStndEd3VkhRRGFuN2xieDRKOUNLYVJtc05WRXg4ZjhVSG1zbkVjOUNSbWI3T1M3aER2STFXZS9tcGZUdUQKWUhIUFN4Q2JQTGVnVE43VjVlSWY5UEJYKzJIZVRmeDNkM0tnS2RoK2cwaUF6cXYvais0SFV3OUV3VEtNUGM4UAp6dWZBemYxcWlkUVV6dHpOaG1mSDA3WXEvaHBHWHRCdkhmVWNpVmRJNlhUdTYrSEg2R2hVMlM1WHd3eHlIcFQzCkFhZjBUR043VUZydHhheE92N1g3OUJkcCt3MUZRd3o1aGJaRGw5THcvKzNYTDVuVEFJWlZPZ1UzcjQ5YlRpMmQKQ2MzbDdVbjhTN2YwVnNZbXphdEdRcmhnNk1PZUJlSUorakJpeDY0K0J1SmtsTXhqN2xvRkIrWjEvMVkwRmNkRgpmcWJoRlpHaWRjb3R1NTgyb3NjQ0F3RUFBYU5GTUVNd0RnWURWUjBQQVFIL0JBUURBZ0trTUJJR0ExVWRFd0VCCi93UUlNQVlCQWY4Q0FRQXdIUVlEVlIwT0JCWUVGSGF4VVUxNTcrbUd6V0pDSXhVQXdoUnRyei81TUEwR0NTcUcKU0liM0RRRUJDd1VBQTRJQkFRQjJvbFRJbE1iWDJOY0NGL3MwWk1qOFV6ZnF2MzJPTVF5UzhwY0lTeUt1ZDBsTgpvQkJpajZWV2wweU51UUtnMFgyOGRvYkV1VVoxT2o3MXovTE9QUERkeXdCR3dMT21BNXREZHN1bnVpWS9jSG9CCnNYd3g3SVdLV04wdmFFY2VDL09TRDRobHBTdFFoaEczK1lLQXdiMWt4bHR6NStJNjlPRjNlakg0WkRBbVFidkoKenZuT2NZRTNhTnI1NnJ6bkpCL0JmcWJSVTMrcUJVL0JUd0RZQ09UUEgxNHVOVkZ0T3BWeWJiSWcydWh3SXZYSApNeGFueSt2WnNRTjdFamNnZk5PcG1LaldYaHFoTXc2cFFMNkM2TWNZUlZBcmE3RUx6N3Vnczh6MGZnRFpicFNJCmJwU1ZUQWJBTUZ5eUplRUk3SktQTnFjTm1hTGsyN21wT25BSzRnMTQKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    server: https://176.123.163.160:6443
  name: zen-neumann-3xw3crs3hngbfdgrbc6b65qrl4
contexts:
- context:
    cluster: zen-neumann-3xw3crs3hngbfdgrbc6b65qrl4
    user: zen-neumann-3xw3crs3hngbfdgrbc6b65qrl4-admin
  name: zen-neumann-3xw3crs3hngbfdgrbc6b65qrl4-admin@zen-neumann-3xw3crs3hngbfdgrbc6b65qrl4
current-context: zen-neumann-3xw3crs3hngbfdgrbc6b65qrl4-admin@zen-neumann-3xw3crs3hngbfdgrbc6b65qrl4
kind: Config
preferences: {}
users:
- name: zen-neumann-3xw3crs3hngbfdgrbc6b65qrl4-admin
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1
      args:
      - get-token
      - --iam-url=https://id.cloud.ru/auth/system/openid/token
      command: cloudlogin
      env:
      - name: CLOUDRU_KEY_ID
        value: "ff82a685101d12556da8396373c0b524"
      - name: CLOUDRU_SECRET_ID
        value: "984fa99f7d5f3bf7d81444969cc453fa"
      installHint: Required to configure kubectl for authentication in your Cloud.ru
        Managed Kubernetes cluster
      interactiveMode: Never
      provideClusterInfo: false
